services:
  api:
    build: .
    ports:
      - "8080:8000"  # Mudando a porta externa para 8080
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rcs_db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - .:/app
    command: >
      sh -c "sleep 5 &&
             alembic upgrade head && 
             python init_db.py &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rcs_db
    ports:
      - "5433:5432"  # Porta externa 5433
    restart: always

volumes:
  postgres_data:
